name: ${project.artifactId}
main: ${package}.${project.artifactId}
version: ${project.version}
author: ${developer}
softdepend: [WorldBorder]

commands:
   randomtp:
      description: RandomTP main command
      aliases: [rtp]

permissions:
    rtp.use:
        description: Use /rtp 
        default: true
    rtp.bypass:
        description: Permits to bypass time limit
        default: op
 